name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'


      - name: Load environment variables
        run: |
          echo "VITE_APP_BASE_URL=/zama_bounty/" >> $GITHUB_ENV
          echo "VITE_LOCAL_IPFS_API_URL=http://localhost:5001" >> $GITHUB_ENV
          echo "VITE_LOCAL_IPFS_GATEWAY_URL=http://localhost:8080" >> $GITHUB_ENV
        
      - name: Load secret environment variables
        run: |
          echo "VITE_DEDICATED_IPFS_URL=${{ secrets.VITE_DEDICATED_IPFS_URL }}" >> $GITHUB_ENV
          echo "VITE_PINATA_JWT=${{ secrets.VITE_PINATA_JWT }}" >> $GITHUB_ENV
        

      - name: Install all dependencies
        run: npm install
    
      - name: Run lint
        run: npm run lint
  
      - name: Clean up node_modules
        run: rm -rf node_modules
  
      - name: Install production dependencies
        run: npm ci --omit=dev

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./dist
